#!/usr/bin/env python3
"""Generate config/rack_slots.yaml from the 'racks:' geometry in
config/warehouse_grid.yaml. Never edit rack_slots.yaml by hand: change the
geometry (warehouse_map_tool.py) or the convention (amr_fleet/core/rack_slots.py)
and re-run:

    python3 scripts/gen_rack_slots.py            # writes config/rack_slots.yaml
    python3 scripts/gen_rack_slots.py --check    # exit 1 if the file is stale
"""
import argparse
import pathlib
import sys

PKG = pathlib.Path(__file__).resolve().parents[1]
sys.path.insert(0, str(PKG))

from amr_fleet.core.rack_slots import (APPROACH_YAW, SECTION_DIRECTION,  # noqa: E402
                                       SECTIONS_PER_FACE, RackSlots)


def render(slots: RackSlots, grid_name: str) -> str:
    f = lambda v: f"{v:.4f}".rstrip("0").rstrip(".") if v != 0 else "0.0"  # noqa: E731
    lines = [
        "# GENERATED by scripts/gen_rack_slots.py from " + grid_name + " - DO NOT EDIT.",
        "# Label '<side>R<section>': rack k north face = side 2k-1, south face = side 2k;",
        "# racks 1..6 left->right, top->bottom; sections 1..%d %s." % (
            SECTIONS_PER_FACE, SECTION_DIRECTION),
        "# approach = face-segment centre pushed W/4 into the aisle, yaw %s." % APPROACH_YAW,
        f"aisle_width_m: {f(slots.aisle_width_m)}",
        f"approach_offset_m: {f(slots.approach_offset_m)}",
        f"sections_per_face: {SECTIONS_PER_FACE}",
        "sides:",
    ]
    for s in slots.side_summary():
        lines.append(
            f"  {s['side']}: {{rack: {s['rack']}, face: {s['face']}, "
            f"face_y: {f(s['face_y'])}, x_min: {f(s['x_min'])}, x_max: {f(s['x_max'])}, "
            f"section_length_m: {f(s['section_length_m'])}, "
            f"approach_y: {f(s['approach_y'])}, approach_row: {s['approach_row']}}}")
    lines.append("slots:")
    for s in slots.slots():
        ax, ay, yaw = s.approach
        lines.append(
            f"  {s.label}: {{side: {s.side}, rack: {s.rack}, face: {s.face}, "
            f"section: {s.section}, x0: {f(s.x0)}, x1: {f(s.x1)}, "
            f"centre: [{f(s.centre[0])}, {f(s.centre[1])}], "
            f"approach: [{f(ax)}, {f(ay)}, {f(yaw)}], "
            f"approach_cell: [{s.approach_cell[0]}, {s.approach_cell[1]}]}}")
    return "\n".join(lines) + "\n"


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--grid", default=str(PKG / "config" / "warehouse_grid.yaml"))
    ap.add_argument("--out", default=str(PKG / "config" / "rack_slots.yaml"))
    ap.add_argument("--check", action="store_true")
    a = ap.parse_args()
    text = render(RackSlots.from_yaml(a.grid), pathlib.Path(a.grid).name)
    out = pathlib.Path(a.out)
    if a.check:
        ok = out.exists() and out.read_text() == text
        print("rack_slots.yaml " + ("up to date" if ok else "STALE"))
        return 0 if ok else 1
    out.write_text(text)
    print(f"wrote {out} ({text.count(chr(10))} lines)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
